### ISSUE TITLE
Need to be able to specify the AWS region

### ISSUE THREAD

**Issue by llewellynb** [jessecoyle/jcredstash#5]
Hi, I needed to a way to specify the AWS region when jcredstash creates the dynamodb & kms clients. Please see the patch at https://drive.google.com/file/d/0B_MKDfXbyPuoeVNVQ2hMbElNblk/view?usp=sharing. The utility worked great apart from this, thanks for writing it.

**Comment by stephanebruckert** [comment]
@jessecoyle can we make a PR and merge this?

**Comment by jessecoyle** [comment]
I'm closing this as I am recommending users to migrate away from Crestash (and this implementation)
