### ISSUE TITLE
Timeline for pushing a 1.X version to Maven Central

### ISSUE THREAD

**Issue by jblair3** [jessecoyle/jcredstash#7]
Hello, just curious if/when you might be planning on pushing an updated 1.X version to Maven Central.  I would be looking to leverage the ability to store secrets with this utility.

Thanks

**Comment by BastianVoigt** [comment]
yeah please....

**Comment by jessecoyle** [comment]
I'm closing this as I am recommending users to migrate away from Crestash (and this implementation)
